version: '3.7'
services:
  node:
    image: node:10
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
    ports:
      - "3000:3000"
    command: /bin/bash -c 'npm install && npm run dev'
    environment:
      HOST: "0.0.0.0"
      REDIS_URL: "redis://redis"
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:5
    ports:
      - "6379:6379"
